### ISSUE TITLE
Is there a way to collect also navigation data from a gridmap?

### ISSUE THREAD

**Issue by Ramshell** [TheFamousRat/GodotFlowField#1]
@TheFamousRat Under the usage info it says that it works by collecting all CollisionShapes, and I wonder if it will take into account the navmeshes or collision shapes info from a GridMap.

**Comment by TheFamousRat** [comment]
Hey @Ramshell,

For now the functionality is not supported. I will add it to my roadmap, but this will likely not be implemented soon ! For now the bulk of the work is targeted at a somewhat workable crowd system. 
More specifically for your question, I think the CollisionsShapes from a GridMap can be added easily, however navmeshes will be a bit more work. So here's which one will be implemented before the other ;)
